k2/k2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("progress_tracker.urls")),
]

k2/progress_tracker/urls.py
from django.urls import path
from .views import (
    LoginView,
    Custom_LogoutView,
    StudentListView,
    UpdateProgressReportView,
    ProgressGraphView,
    MarksheetView,
    AssignmentReportView,
    OverallProgressView,
    StudentDetailView,
)

app_name = "progress_tracker"

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("logout/", Custom_LogoutView.as_view(), name="logout"),
    path("students/", StudentListView.as_view(), name="student_list"),
    path(
        "update_progress_report/<int:pk>/",
        UpdateProgressReportView.as_view(),
        name="update_progress_report",
    ),
    path("progress_graph/", ProgressGraphView.as_view(), name="progress_graph"),
    path("marksheet/", MarksheetView.as_view(), name="marksheet"),
    path(
        "assignmnet_report/", AssignmentReportView.as_view(), name="assignmnet_report"
    ),
    path("overall_progress/", OverallProgressView.as_view(), name="overall_progress"),
    path(
        "student_detail/<str:username>/",
        StudentDetailView.as_view(),
        name="student_detail",
    ),
]

k2/progress_tracker/models.py
# progress_report/models.py

from django.db import models
from django.db.models import Avg


class Trainee(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50)
    name = models.CharField(max_length=100)

    @property
    def get_progress(self):
        progress_reports = ProgressReport.objects.filter(trainee=self)

        if progress_reports:
            attendance_aggregate = progress_reports.aggregate(average=Avg("attendance"))
            average_attendance = attendance_aggregate["average"]
            attendance_percentage = average_attendance / 100.0
        else:
            attendance_percentage = 0

        if progress_reports:
            marks_aggregate = progress_reports.aggregate(average=Avg("marks"))
            average_marks = marks_aggregate["average"]
            marks_percentage = average_marks / 100.0
        else:
            marks_percentage = 0

        if progress_reports:
            assignment_aggregate = progress_reports.aggregate(average=Avg("assignment"))
            average_assignment = assignment_aggregate["average"]
            assignment_percentage = average_assignment / 100.0
        else:
            assignment_percentage = 0

        return (attendance_percentage + marks_percentage + assignment_percentage) / 3

    @property
    def progress(self):
        progress_reports = ProgressReport.objects.filter(trainee=self)
        percentages = [report.attendance / 100.0 for report in progress_reports]

        return percentages

    @property
    def get_marks(self):
        progress_reports = ProgressReport.objects.filter(trainee=self)
        marks = [report.marks / 100.0 for report in progress_reports]
        return marks

    @property
    def get_assignment(self):
        progress_reports = ProgressReport.objects.filter(trainee=self)
        assignments = [report.assignment / 100.0 for report in progress_reports]
        return assignments

    def __str__(self):
        return self.username


class ProgressReport(models.Model):
    trainee = models.ForeignKey(Trainee, on_delete=models.CASCADE)
    week_number = models.PositiveIntegerField()
    attendance = models.PositiveIntegerField()
    assignment = models.PositiveIntegerField()
    marks = models.PositiveIntegerField()
    comments = models.TextField()

k2/progress_tracker/forms.py
from django import forms
from .models import ProgressReport


class ProgressReportForm(forms.ModelForm):
    class Meta:
        model = ProgressReport
        fields = ["marks", "comments"]

    def __init__(self, *args, **kwargs):
        super(ProgressReportForm, self).__init__(*args, **kwargs)
        self.fields["marks"].widget.attrs.update({"class": "form-control"})
        self.fields["comments"].widget.attrs.update({"class": "form-control"})

k2/progress_tracker/views.py
"""This is the view for progress_report app"""

from django.contrib.auth import login
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DetailView, TemplateView
from django.http import Http404

from .models import Trainee, ProgressReport
from .forms import ProgressReportForm


class LoginView(LoginView):
    template_name = "progress_tracker/login.html"

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return redirect(reverse_lazy("progress_tracker:overall_progress"))


class Custom_LogoutView(LogoutView):
    next_page = reverse_lazy("progress_tracker:login")


class StudentListView(LoginRequiredMixin, ListView):
    model = ProgressReport
    template_name = "progress_tracker/student_list.html"
    context_object_name = "progress_reports"
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.select_related("trainee")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["trainees"] = Trainee.objects.all()
        return context


class UpdateProgressReportView(UpdateView):
    model = ProgressReport
    form_class = ProgressReportForm
    template_name = "progress_tracker/update_progress_report.html"
    success_url = reverse_lazy("progress_tracker:student_list")

    # def form_valid(self, form):
    #     form.instance.week_number = 1
    #     return super().form_valid(form)


class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Trainee
    template_name = "progress_tracker/student_detail.html"
    context_object_name = "trainee"

    def get_object(self, queryset=None):
        username = self.kwargs.get("username", None)
        trainees = Trainee.objects.filter(username=username)

        if not trainees.exists():
            raise Http404("Trainee not found")

        return trainees.first()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["progress_reports"] = ProgressReport.objects.filter(trainee=self.object)
        return context


class ProgressGraphView(LoginRequiredMixin, TemplateView):
    template_name = "progress_tracker/progress_graph.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_trainees = Trainee.objects.all()
        context["attendance_data"] = {
            trainee.username: trainee.progress for trainee in all_trainees
        }
        return context


class MarksheetView(LoginRequiredMixin, TemplateView):
    template_name = "progress_tracker/marksheet.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_trainees = Trainee.objects.all()
        context["mark_data"] = {
            trainee.username: trainee.get_marks for trainee in all_trainees
        }
        return context


class AssignmentReportView(LoginRequiredMixin, TemplateView):
    template_name = "progress_tracker/assignmnet_report.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_trainees = Trainee.objects.all()
        context["assignment_data"] = {
            trainee.username: trainee.get_assignment for trainee in all_trainees
        }
        return context


class OverallProgressView(LoginRequiredMixin, TemplateView):
    template_name = "progress_tracker/overall_progress.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_trainees = Trainee.objects.all()
        context["overall_data"] = {
            trainee.username: trainee.get_progress for trainee in all_trainees
        }
        return context

k2/progress_tracker/templates/progress_tracker/assignmnet_report.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        .green-box {
            width: 25px;
            height: 25px;
            background-color: green;
            border: 1px solid black;
            position: relative;
        }

        .tooltip-text {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            color: white;
            font-size: 14px;
            display: none;
        }

        .green-box:hover .tooltip-text {
            display: block;
        }

        .back-button {
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }

        .back-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
   {% extends "progress_tracker/base.html" %}

   {% block content %}
    <div class="container mt-4">
        <h1>Assignment </h1>
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Trainee</th>
                    <th scope="col">W1</th>
                    <th scope="col">W2</th>
                    <th scope="col">W3</th>
                    <th scope="col">W4</th>
                    <th scope="col">W5</th>
                    <th scope="col">W6</th>
                    <th scope="col">W7</th>
                    <th scope="col">W8</th>
                    <th scope="col">W9</th>
                    <th scope="col">W10</th>
                </tr>
            </thead>
            <tbody class= 'border border-collapse'>
                {% for username, assignments in assignment_data.items %}
                    <tr>
                        <td>{{ username }}</td>
                        {% for assignment in assignments %}
                            <td>
                                <div class="green-box" style="opacity: {{ assignment }};">
                                    <div class="tooltip-text">{{ assignment }}%</div>
                                </div>
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


    {% endblock %}
</body>

</html>

k2/progress_tracker/templates/progress_tracker/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <style>
      .navbar-brand {
        flex-grow: 0;
        text-align: center;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #7952b3;">
      <div class="container-fluid">
        <h4 class="nav-item navbar-brand" style="margin-right: 10px;">K2</h4>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse text-light" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="/progress_graph/" style="color: white;">Attendance Summary %<span class="sr-only"></span></a>
            </li>
            <li class="nav-item ml-2 ml-2 active">
              <a class="nav-link" href="/assignmnet_report/" style="color: white;">Assignment Submissions % <span class="sr-only"></span></a>
            </li>
            <li class="nav-item ml-2 active">
              <a class="nav-link" href="/marksheet/" style="color: white;">Mentor Marks <span class="sr-only"></span></a>
            </li>
            <li class="nav-item ml-2 active">
              <a class="nav-link" href="/overall_progress/" style="color: white;">Overall Performance <span class="sr-only"></span></a>
            </li>
            <li class="nav-item ml-2 active">
              <a class="nav-link" href="/students/" style="color: white;">Detailed Progress Reports <span class="sr-only"></span></a>
            </li>
          </ul>

          <ul class="navbar-nav">
            <li class="nav-item active ml-auto">
              <a class="btn btn-outline-dark" href="/logout/">Logout <span class="sr-only"></span></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
  </body>
</html>

k2/progress_tracker/templates/progress_tracker/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"></head>
<body>
    <div  class="p-3 border border-dark">
        <h2>Login</h2>
        <form class="p-3 " method="post" action="{% url 'progress_tracker:login' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
    </div>
</body>
</html>

k2/progress_tracker/templates/progress_tracker/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
</head>
<body>
    <h2>Logout</h2>
    <p>You have been logged out. <a href="{% url 'progress_tracker:login' %}">Login again</a>.</p>
</body>
</html>

k2/progress_tracker/templates/progress_tracker/marksheet.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <style>
        .green-box {
            width: 25px;
            height: 25px;
            background-color: green;
            border: 1px solid black;
            position: relative;
        }

        .tooltip-text {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            color: white;
            font-size: 14px;
            display: none;
        }

        .green-box:hover .tooltip-text {
            display: block;
        }

        .back-button {
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }

        .back-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>

    {% extends "progress_tracker/base.html" %}

    {% block content %}
    <div class="container mt-4">
        <h1>Mentor Marks</h1>
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Trainee</th>
                    <th scope="col">W1</th>
                    <th scope="col">W2</th>
                    <th scope="col">W3</th>
                    <th scope="col">W4</th>
                    <th scope="col">W5</th>
                    <th scope="col">W6</th>
                    <th scope="col">W7</th>
                    <th scope="col">W8</th>
                    <th scope="col">W9</th>
                    <th scope="col">W10</th>
                </tr>
            </thead>
            <tbody class=' border border-collapse'>
                {% for username, marks in mark_data.items %}
                    <tr>
                        <td>{{ username }}</td>
                        {% for mark in marks %}
                            <td>
                                <div class="green-box" style="opacity: {{ mark }};">
                                    <div class="tooltip-text">{{ mark }}%</div>
                                </div>
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% endblock %}
</body>

</html>

k2/progress_tracker/templates/progress_tracker/overall_progress.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        .green-box {
            width: 25px;
            height: 25px;
            background-color: green;
            border: 1px solid black;
            position: relative;
        }

        /* Add tooltip styling */
        .tooltip-text {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            color: white;
            font-size: 14px;
            display: none;
        }

        .green-box:hover .tooltip-text {
            display: block;
        }

        .back-button {
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }

        .back-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>


    
   {% extends "progress_tracker/base.html" %}

   {% block content %}
    <div class="container mt-4">
        <h1>Overall Progress</h1>
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Trainee</th>
                    <th scope="col">Overall</th>
                </tr>
            </thead>
          <tbody>
            <tbody>
                {% for username, overall_average in overall_data.items %}
                    <tr>
                        <td>
                            <a href="{% url 'progress_tracker:student_detail' username=username %}">
                                {{ username }}
                            </a>
                        </td>
                        <td>
                            <div class="green-box" style="opacity: {{ overall_average }};">
                                <!-- Add tooltip text inside the green box -->
                                <div class="tooltip-text">{{ overall_average }}%</div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


    {% endblock %}

</body>

</html>

k2/progress_tracker/templates/progress_tracker/progress_graph.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
      .green-box {
        width: 25px;
        height: 25px;
        background-color: green;
        border: 1px solid black;
        position: relative;
        cursor: pointer;
      }
      .back-button {
        margin-top: 20px;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
      }

      .back-button:hover {
        background-color: #0056b3;
      }

      .tooltip-text {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        color: white;
        font-size: 14px;
        display: none;
      }

      .green-box:hover .tooltip-text {
        display: block;
      }
    </style>
  </head>
  <body>


    
   {% extends "progress_tracker/base.html" %}

   {% block content %}
    <div class="container mt-4">
      <h1>Attendance Sheet</h1>
      <table class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th  scope="col">Trainee</th>
            <th  scope="col">W1</th>
            <th  scope="col">W2</th>
            <th  scope="col">W3</th>
            <th  scope="col">W4</th>
            <th  scope="col">W5</th>
            <th  scope="col">W6</th>
            <th  scope="col">W7</th>
            <th  scope="col">W8</th>
            <th  scope="col">W9</th>
            <th  scope="col">W10</th>
          </tr>
        </thead>
        <tbody class="border border-collapse">
          {% for username, percentages in attendance_data.items %}
            <tr>
              <td>{{ username }}</td>
              {% for percent in percentages %}
                <td>
                  <div class="green-box" style="opacity: {{ percent }};">
                    <div class="tooltip-text">{{ percent }}%</div>
                  </div>
                </td>
              {% endfor %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    
    {% endblock %}
  </body>
</html>

k2/progress_tracker/templates/progress_tracker/student_detail.html
{% extends 'progress_tracker/base.html' %}

{% block content %}
  <div class="container mt-4">
    <h1>{{ trainee.name }}'s Progress Details</h1>
    <br />
    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th class="text-center" scope="col">Week Number</th>
          <th class="text-center" scope="col">Attendance %</th>
          <th class="text-center" scope="col">Assignment %</th>
          <th class="text-center" scope="col">Marks By Mentor</th>
          <th class="text-center" scope="col">Comments</th>
          <th class="text-center" scope="col">Update</th>
        </tr>
      </thead>
      <tbody>
        {% for progress_report in progress_reports %}
          <tr>
            <td class="text-end">{{ progress_report.week_number }}</td>
            <td class="text-end">{{ progress_report.attendance }}</td>
            <td class="text-end">{{ progress_report.assignment }}</td>
            <td class="text-end">{{ progress_report.marks }}</td>
            <td >{{ progress_report.comments }}</td>
            <td class="text-end">
              <a href="{% url 'progress_tracker:update_progress_report' progress_report.pk %}" class="btn btn-outline-primary">Update</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="d-flex" style="justify-content: center;">
    <a class="back-button" href="{% url 'progress_tracker:overall_progress' %}">Back to Overall Progress</a>
  </div>
{% endblock %}

k2/progress_tracker/templates/progress_tracker/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Progress Report Detail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd; 
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        form {
            margin: 10px 0;
        }

        button {
            padding: 5px 10px;
            cursor: pointer;
        }

        textarea {
            width: 100%;
            height: 80px;
        }
        nav-link {
            color: white;
        }
    </style>
</head>
<body>

   {% extends "progress_tracker/base.html" %}

   {% block content %}
</br>
<div p-3>
    <h2>Progress Report Detail</h2>

    <table class="table table-bordered">
        <thead class="thead-dark">
        <tr>
            <th class="text-center" scope="col">ID</th>
            <th class="text-center" scope="col">Username</th>
            <th class="text-center" scope="col">Trainee</th>
            <th class="text-center" scope="col">Attendance %</th>
            <th class="text-center" scope="col">Assignment %</th>
            <th class="text-center" scope="col">Marks By Mentor</th>
            <th class="text-center" scope="col">Comments</th>
            <th class="text-center" scope="col">Update</th>

        </tr>
        {% for progress_report in progress_reports %}
            <tr>
                <td class="text-end">{{ progress_report.trainee.id }}</td>
                <td >{{ progress_report.trainee.username }}</td>
                <td >{{ progress_report.trainee.name }}</td>
                <td class="text-end">{{ progress_report.week_number }}</td>
                <td class="text-end">{{ progress_report.attendance }}</td>
                <td class="text-end">{{ progress_report.assignment }}</td>
                <td class="text-end">{{ progress_report.marks }}</td>
                <td>{{ progress_report.comments }}</td>
                <td class="text-end">
                    <a href="{% url 'progress_tracker:update_progress_report' progress_report.pk %}" class="btn btn-outline-primary">Update</a>
                </td>
            </tr>
        {% endfor %}
    </table>
</br>
     <div class="d-flex justify-content-center">

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}"     class="btn-outline-primary">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}"  class="btn-outline-primary">last &raquo;</a>
            {% endif %}
        </span>
    </div>

</div>
    {% endblock %}

</body>
</html>

k2/progress_tracker/templates/progress_tracker/update_progress_report.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Progress Report</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>
    
   {% extends "progress_tracker/base.html" %}

   {% block content %}
    <div class="container mt-5">
        <div class="p-3 bg-light border rounded">
            <h2 class="mb-4">Update Progress Report</h2>
            <form method="post" action="{% url 'progress_tracker:update_progress_report' pk=object.pk %}">
            {% csrf_token %}
                <div class="mb-3 form-control">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
    {% endblock %}
    
</body>
</html>